### PR TITLE
Correct calculation of factory trim for MPU9250.

### PR DESCRIPTION
**Pull request by simonjwright**
The expected result of the self test is factory-programmed in a byte
value using
  expected = 2620 * (1.01 ** byte-value)
and we use a table lookup to avoid exponentiation.

The previous code was off-by-one and would have resulted in
divide-by-zero if the byte value was zero.

  * components/src/motion/mpu9250/mpu9250.ads (MPU9250_ST_TB): index
      from 0 .. 255 instead of 1 .. 256.
  * components/src/motion/mpu9250/mpu9250.adb (MPU9250_Self_Test): use
      the Self_Test value read from the device (0 .. 255) to index
      MPU9250_ST_TB directly.

See https://github.com/kriswiner/MPU-9250/blob/master/MPU9250BasicAHRS.ino line 987 ff.

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
This looks good to me. Did you try with the Crazyflie?

**Comment by simonjwright** [comment]
I don’t have a Crazyflie, but I _do_ have an AdaRacer board and an MPU9250 breakout/STM32F407 disco, and the code works fine with both of them.

**Comment by Fabien-Chouteau** [comment]
> I'll let you know when we are ready.

We are!

Hi Simon, we are now asking contributors to sign a Contribution License Agreement (more info here: https://github.com/AdaCore/contributing-howto) and we use cla-assistant to allow for online signature.

Click on the "Details" link to right of the " Contributor License Agreement is not signed yet. " message if you want to be our first beta tester ;)

Thanks,

**Comment by simonjwright** [comment]
Looks as though I signed the CLA OK! Not sure about the conflict - I used `Unsigned_16`, you have `Uint16`; I don’t see why this leads to a conflict (though `Unsigned_16` is probably _wrong_, given the recent revision of `Uintn` declarations).

**Comment by Fabien-Chouteau** [comment]
The conflict come from the fact that we changed the code in parallel.

I suggest you rebase your patch on a fresh master branch and then update your mpu9250-factory-trim branch. 

Thanks,

**Comment by Fabien-Chouteau** [comment]
Thanks Simon!

**Comment by simonjwright** [comment]
Glad it worked - I thought I’d made a complete mess of it by not reading your "rebase .. on a fresh master branch" properly. I will go away and learn about rebase.

**Comment by Fabien-Chouteau** [comment]
Well, there was a couple of rebase and merge commits in your branch that could be avoided if you do

`$ git pull --rebase origin master`
or
`$ git pull --rebase https://github.com/AdaCore/Ada_Drivers_Library/ master`

But it's not a big deal.

**Pull request merged**
