### PR TITLE
WIP: interface: Begin implementation of device/host interface

### PR DESCRIPTION
**Pull request by DarkCookies**

### CODE REVIEW

**Comment by DarkCookies** [comment]
Sorry, was not meant to be there

**Comment by Fabien-Chouteau** [comment]
Hi @DarkCookies , I see that you are working on USB support. I have a prototype implementation in my fork: https://github.com/Fabien-Chouteau/Ada_Drivers_Library/tree/stm32_usb

**Comment by DarkCookies** [comment]
Hi, thank you for this. I haven't seen it yet. I will take a look at it.

**Comment by Fabien-Chouteau** [comment]
I strongly suggest that you use this prototype as it is already working and I spent some time designing this interface.

**Comment by fayak** [comment]
:upside_down_face:

**Pull request closed without merging**
