### PR TITLE
Add a known good Australian micro:bit distributor.

### PR DESCRIPTION
**Pull request by EclecticSoftwareEngineer**
Minor proofing fixes to the text.

### CODE REVIEW

**Comment by EclecticSoftwareEngineer** [comment]
screenshot_2019-01-02 cla assistant

**Comment by Fabien-Chouteau** [comment]
Thank you @EclecticSoftwareEngineer,

We will have a look as soon as possible.

**Comment by Fabien-Chouteau** [comment]
Hi @EclecticSoftwareEngineer,

I checked in CLA-assistant and you are indeed listed as having signed the CLA.

I think the problem might come from the fact the patch is attributed to two "identities": `David K. Trudgett authored and David K. Trudgett ` as you can see here: https://github.com/AdaCore/Ada_Drivers_Library/pull/285/commits

Is it possible that the name and/or email address in commit are different than those of your GitHub account?

Sorry to bother you with this, but I want to understand what is going on here.

Thanks,

**Comment by EclecticSoftwareEngineer** [comment]
Thanks, Fabien,

I will look into this. It does look like two identities there somehow (at
present, I'm not sure how that would happen).

I'll get back to you when I have had a chance to investigate.

Kind regards,
David Trudgett

**Pull request closed without merging**
