### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by evilspacepirate**
Add component: BlueNRG-MS

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Hi,
Do you plan to implement an Ada firmware for this device or a driver to control it from outside?

I'm also curious to know in which project your are going to use this chip :)

**Comment by evilspacepirate** [comment]
Fabien,

The goal is to control the BlueNRG-MS component from the outside using an
STM32F407 chip.

John

**Comment by Fabien-Chouteau** [comment]
> The goal is to control the BlueNRG-MS component from the outside using an STM32F407 chip.

Thanks, I will apply your patch. Don't hesitate to give us progress report or to do intermediate pull-requests to get some early feedback.

**Comment by evilspacepirate** [comment]
Thanks Fabien.

**Pull request merged**
