### PR TITLE
Use relative path in .gitmodules

### PR DESCRIPTION
**Pull request by orgads**
Let the user choose how to clone.

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Hi @orgads,

Thanks for your contribution.

I'm think I'm OK with this change. Can you tell us what to you mean by "choose how to clone"? What can you do differently with a relative path?

Thanks,

**Comment by orgads** [comment]
You can clone using ssh, or even clone from a different fork, and use the corresponding submodule.

For example, if someone forks both repos, and changes both of them (including the reference), this won't work without using a relative path.

**Comment by Fabien-Chouteau** [comment]
> For example, if someone forks both repos, and changes both of them (including the reference), this won't work without using a relative path.

The corollary is that you are forced to clone both repositories, right?

**Comment by orgads** [comment]
>> For example, if someone forks both repos, and changes both of them (including the reference), this won't work without using a relative path.

> The corollary is that you are forced to clone both repositories, right?

Not necessarily. I usually clone from the _original_ repo, then I add my fork with `git remote add my <address>`. In that case, `git submodule update --init` and `git clone --recursive` will use the original repo.

**Comment by Fabien-Chouteau** [comment]
That sounds a bit too difficult for those who are not git/GitHub expert.
I think we are going to keep the current URL unless many people request this.

Thanks,

**Pull request closed without merging**
