### PR TITLE
Unify access to classwide type names

### PR DESCRIPTION
**Pull request by pat-rogers**
An access-to-classwide type is much like a pointer-to-baseclass in C++, in that the access values can designate any type in the derivation class. **Any** type. A good way to name such types then, and one that does not redundantly include the "_Access" or "_Ref", is to add the prefix "Any_" to the designated type name, eg Any_GPIO_Point or Any_I2C_Port. If we are consistent the reader will immediately know what they are getting.

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
IMO, it would be OK for a class type:
`subtype Any_I2C_Port is I2C_Port'Class;`
But for an access type we lose some information and I don't like to "hide" that something is an access.

**Comment by pat-rogers** [comment]
In practice, though, to be used in this way ("any" of the types in a class) it must be an access type, so there really is nothing lost.   All the more so when the naming convention is known.
(I've never seen a subtype declared like that, since 1995.)

**Comment by pat-rogers** [comment]
I feel strongly that the current naming scheme is inadequate and slightly misleading, and have used the proposed scheme for many years without difficulties.

**Comment by Fabien-Chouteau** [comment]
OK. I don't agree but if you feel strongly about it I'm willing to try :)

**Comment by pat-rogers** [comment]
On 12/22/2016 3:54 AM, Fabien Chouteau wrote:
> OK. I don't agree but if you feel strongly about it I'm willing to try :)

Thanks.  I appreciate that.  :-)

**Pull request merged**
