### PR TITLE
Added Frown, Cross, Checkmark and Heart symbols

### PR DESCRIPTION
**Pull request by Feqzz**
Added four more symbols to play around with.

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Hello @Feqzz, thanks for your contribution :)

Before we can merge this pull request you have to remove the trailing whitespaces in the source file:
```
microbit-display-symbols.adb:125:01: (style) trailing spaces not permitted
microbit-display-symbols.adb:136:01: (style) trailing spaces not permitted
microbit-display-symbols.adb:140:01: (style) trailing spaces not permitted
microbit-display-symbols.adb:153:01: (style) trailing spaces not permitted
microbit-display-symbols.adb:157:01: (style) trailing spaces not permitted
microbit-display-symbols.adb:166:01: (style) trailing spaces not permitted
microbit-display-symbols.adb:170:01: (style) trailing spaces not permitted
```

**Comment by Fabien-Chouteau** [comment]
I am sorry @Feqzz the build failures are my mistake.

It's fixed now, can you rebase your change on master?

**Review by Fabien-Chouteau — APPROVED** [review]

**Comment by Fabien-Chouteau** [comment]
Thank you @Feqzz and sorry for the extra step.

**Comment by Feqzz** [comment]
@Fabien-Chouteau. No problem!

**Pull request merged**
