### PR TITLE
Correct scan mode enabling in configure routines

### PR DESCRIPTION
**Pull request by pat-rogers**
Also ensures consistent external trigger and enabler in subsequent calls; minor simplifications

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
There's something strange with the pull request. Can you try to do a pull --rebase and then push the branch again?

**Comment by pat-rogers** [comment]
On 2/1/2017 10:06 AM, Fabien Chouteau wrote:
> There's something strange with the pull request. Can you try to do a pull --rebase and then push the branch again?

OK, just did  and pushed (a new branch).

**Comment by Fabien-Chouteau** [comment]
These "merge" commits probably come when you do a pull without the --rebase option. I don't think it will cause a problem but if we can get rid of them that would be better.

**Comment by pat-rogers** [comment]
On 2/1/2017 10:21 AM, Fabien Chouteau wrote:
> These "merge" commits probably come when you do a pull without the --rebase option. I don't think it will cause a problem but if we can get rid of them that would be better.

I'm using TortoiseGit to do most things, including the pull (because it 
is convenient) and can enable the "Rebase after fetch" option when doing so.

**Comment by Fabien-Chouteau** [comment]
It looks like it doesn't work how it's supposed to.

For the next time, can you try to add this to your config file:

`[branch]
  autosetuprebase = always`

or
`$ git config --global branch.autosetuprebase always`

**Comment by pat-rogers** [comment]
On 2/1/2017 11:17 AM, Fabien Chouteau wrote:
> It looks like it doesn't work how it's supposed to.
>
> For the next time, can you try to add this to your config file:
>
> `[branch]
>   autosetuprebase = always`
>
> or
> `$ git config --global branch.autosetuprebase always`

Done (the latter).

**Pull request closed without merging**
