### PR TITLE
HAL: Make UInt8|16|32 derived from Interfaces types rather than subtypes

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**
As discussed in #141.

This remove the dependency on the Interfaces package which simplify the
use of HAL types.

Also remove Byte and Bit subtype.

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
@pat-rogers I didn't check the STM32 drivers demo yet.

**Comment by Fabien-Chouteau** [comment]
> type UInt1 is mod 2**1;
> subtype Bit is UInt1;

We can do one or the other, I don't have a strong opinion here. But I don't think it's a good idea to have both.

**Comment by pat-rogers** [comment]
On 2/14/2017 4:59 AM, Fabien Chouteau wrote:
>> type UInt1 is mod 2**1;
>> subtype Bit is UInt1;
>
> We can do one or the other, I don't have a strong opinion here. But I don't think it's a good idea to have both.

OK. I think you were right to name that one Bit originally, because it 
is so much more readable (and is unambiguous, unlike byte etc.).

**Comment by Fabien-Chouteau** [comment]
Anyone else want's to comment on the UInt1 vs Bit discussion? Otherwise I will revert to Bit.

**Pull request merged**
