### PR TITLE
Re-introduce the Cortex-M layer of projects.

### PR DESCRIPTION
**Pull request by lambourg**
This makes explicit the MCU family

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
We have to find a better solution for all those obj and lib directories. It's getting ridiculous :)

**Comment by lambourg** [comment]
> Le 17 août 2016 à 18:44, Fabien Chouteau <notifications@github.com> a écrit :
> 
> We have to find a better solution for all those obj and lib directories. It's getting ridiculous :)

Simple one would be for gprbuild to create directories by default :D

**Comment by Fabien-Chouteau** [comment]
> Simple one would be for gprbuild to create directories by default :D

Let's try to make it happen :)

**Comment by pat-rogers** [comment]
On 8/17/2016 11:44 AM, Fabien Chouteau wrote:
> We have to find a better solution for all those obj and lib directories. It's getting ridiculous :)


Do we also still have the problem in which a fair amount of code is 
recompiled every time a build is invoked?

**Comment by lambourg** [comment]
> Le 17 août 2016 à 20:46, Pat Rogers <notifications@github.com> a écrit :
> 
> On 8/17/2016 11:44 AM, Fabien Chouteau wrote:
> > We have to find a better solution for all those obj and lib directories. It's getting ridiculous :)
> 
> 
> Do we also still have the problem in which a fair amount of code is 
> recompiled every time a build is invoked?

Normally, with my change in project organization, it's all fixed in the library itself.

Note that those were recompiled only upon runtime or build type change (or
different board used).

Now within the library, all those configuration have dedicated folders, hence
the huge number of those.

**Pull request merged**
