### PR TITLE
Added initial UART support

### PR DESCRIPTION
**Pull request by adnio**
I dind't see any implementation of HAL.UART for nrf51 so I made a simple one based on the datasheet.

P.D. Sorry I accidentally closed the last pull request.

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Hi @adnio , I would prefer if you re-open the previous PR #262.

I think you should be able to do that.

**Comment by adnio** [comment]
After force pushing, the commit linked to the PR was lost and I made a new one. In this case I don't know any way to reopen the PR. If you know how to do it please tell me and I will try it.

Thank you

**Comment by Fabien-Chouteau** [comment]
I though you would be able to do it. Anyway it is not a huge problem let's continue with this one.

Thanks for the modifications. You have some cleanup to de before I can merge this.

First you have to rebase your branch on the current master:
```
$ git pull --rebase https://github.com/AdaCore/Ada_Drivers_Library.git master
```

You also have to merge all you changes into a single commit.

Thanks

**Comment by adnio** [comment]
Now it is rebased against the newest commit of the Adacore repository. Please confirm it is OK.

Thank you.

**Comment by Fabien-Chouteau** [comment]
Sorry @adnio now that the branch community_2018 has been merged and deleted, this pull-request is not working.

You can edit the pull-request to select the `base` branch. See the `Edit` button to the right of the pull-request title.

Thanks,

**Comment by Fabien-Chouteau** [comment]
I closed this by mistake

**Comment by Fabien-Chouteau** [comment]
@adnio I changed the base branch for this pull request because `community_2018` was deleted after merge. 

It looks like it made things worst...
Can you try again:
```
$ git pull --rebase https://github.com/AdaCore/Ada_Drivers_Library.git master
```

Thanks for your patience, I'm sorry for the erratic workflow...

**Comment by adnio** [comment]
I rebased it, I think it is OK now. Please tell me if there is something wrong.

Thanks @Fabien-Chouteau

**Comment by Fabien-Chouteau** [comment]
Hi @adnio 

No it's still not correct. At this point you might want to backup your code and start from fresh repo.

Regards,

**Pull request closed without merging**
