### PR TITLE
various F4 I2C changes, mostly internal simplifying

### PR DESCRIPTION
**Pull request by pat-rogers**
add postcondition to Set_State.
change internal routine name from Wait_Flag to Wait_Until_Flag, to avoid semantics confusion.
simplify internal deadline calculations.
misc formatting.

### CODE REVIEW

**Comment by pat-rogers** [comment]
continuous-integration/appveyor/branch — AppVeyor build failed , apparently due to taking too long

**Comment by pat-rogers** [comment]
How do I deal with the appveyor timeout (exceeding the time allotted by our plan)?

**Comment by Fabien-Chouteau** [comment]
> How do I deal with the appveyor timeout (exceeding the time allotted by our plan)?

It's true that the build all script takes a lot of time, this is because we have to clean the object file before compiling with a different run-time. So we recompile everything at least  a dozen times...
I hope to improve this with the future project files generated from Kconfig. 

For now, did you try to run the tests on your machine?

**Comment by pat-rogers** [comment]
On 12/5/2017 6:36 AM, Fabien Chouteau wrote:
>     How do I deal with the appveyor timeout (exceeding the time allotted
>     by our plan)?
> 
> It's true that the build all script takes a lot of time, this is because 
> we have to clean the object file before compiling with a different 
> run-time. So we recompile everything at least a dozen times...
> I hope to improve this with the future project files generated from Kconfig.
> 
> For now, did you try to run the tests on your machine?

No (I didn't realize it would work locally). Where should I look for 
instructions?

**Comment by Fabien-Chouteau** [comment]
> Where should I look for instructions?

I we don't have instructions for this, but it's fairly simple. Just run the script: `./scripts/build_all_examples.py`.

**Pull request merged**
